http:
  port: 8080

https:
  port: 8443
  tls:
    default:
      key: /app/certs/server.key
      cert: /app/certs/server.crt
      ca: 
        - /app/certs/ca.crt
      requestCert: true
      rejectUnauthorized: true

admin:
  port: 9876
  host: 0.0.0.0

apiEndpoints:
  backend:
    paths:
      - "/api/backend"
      - "/api/backend/*"
  dashboard:
    paths:
      - "/"
      - "/*"

serviceEndpoints:
  backend:
    url: "http://backend:5000"
  dashboard:
    url: "http://edge-dashboard:4000"

policies:
  - proxy

pipelines:
  backendPipeline:
    apiEndpoints:
      - backend
    policies:
      - proxy:
          - action:
              serviceEndpoint: backend
              changeOrigin: true
              stripPath: true
  dashboardPipeline:
    apiEndpoints:
      - dashboard
    policies:
      - proxy:
          - action:
              serviceEndpoint: dashboard
              changeOrigin: true
